export const CART_ACTION_TYPES = {
  SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
  SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
  SET_CART_COUNT: 'cart/SET_CART_COUNT',
  SET_CART_TOTAL: 'cart/SET_CART_TOTAL',
};

// export const CART_ACTION_TYPES = {
//   // SET_IS_CART_OPEN: 'cart/SET_IS_CART_OPEN',
//   TOGGLE_CART_VISIBILITY: 'cart/TOGGLE_CART_VISIBILITY',
//   // SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
//   ADD_TO_CART: 'cart/ADD_TO_CART',
//   REMOVE_FROM_CART: 'cart/REMOVE_FROM_CART',
//   CLEAR_FROM_CART: 'cart/CLEAR_FROM_CART',
// };
